### ISSUE TITLE
Running  "setup_twitter_oauth" creating 2-3 issues. How do I solve it?

### ISSUE THREAD

**Issue by priyaII** [dipanjanS/learning-social-media-analytics-with-r#2]
When I run this:
`> setup_twitter_oauth(consumer_key = CONSUMER_KEY, consumer_secret = CONSUMER_SECRET)`

Output 1 - 
```
[1] "Using browser based authentication"
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
```

**Comment by priyaII** [comment]
Running this has helped me out.

`install.packages(c("devtools", "rjson", "bit64", "httr"))`

Please share any other suggestions

**Comment by raghavbali** [comment]
@priyaII The error is usually associated with network issues. Are you executing the code behind a proxy/firewall? 

It would be good if you can share the actual stack-trace (along with sequence of code you executed) to better debug this issue. IMHO if the issue was related to missing packages, the error should have been different.
